---
title: "A visual illustration of noncommutative and nonassociative velocity addition in special relativity"
author: "Robin Hankin"
date: "`r Sys.Date()`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Nonassociative noncommutative velocity addition}
output: knitr:::html_vignette
---

This short vignette shows how the *lorentz* package may be used to
produce visual devices to show noncommutative and nonassociative
velocity addition in special relativity.

```{r,echo=FALSE}
library("lorentz")
```


```{r fc1, fig.cap='Failure of commutativity---specifically, the  failure of the parallelogram law.  Consider the bold paralellogram,  which shows four legs of a parallelogramular (that is, not  rectangular) path .  If the parallelogram law for velocities were  exact (as it is for the classical case), then the path would be  closed.  In the diagram, the first, third, and fourth legs (respectively, purple, red, and blue) are a single three-velocity, while the second leg (black) is a linear *sequence* of three-velocities.  As the speed of the third leg increases, the parallelogram law becomes more and more inaccurate, as indicated by the position of the blue circle which shows the three-velocity of the resultant; classically, all blue circles would be at the origin'}
comm_fail1( u = as.3vel(c(0.4,0,0)), v =
  as.3vel(c(0.4,-0.2,0)) + as.3vel(c(-0.4,0.6,0)) *
  seq(from=0,to=3,len=28) )

```

```{r fc2, fig.cap='Failure of commutativity, mark 2.  If the parallelogram law holds, the order of velocity addition would not matter.  Consider the bold parallelogram, which shows two velocity additions: black then blue, and blue then black.  Classically, these are the same but relativistic mechanics there is a small mismatch, shown as a red line.  The black velocities are single, but the blue velocities are a linear sequence of three-velocities.  As the speed of the blue velocities increases, the mismatch becomes larger and larger'}
comm_fail2( u = as.3vel(c(0.4,0,0)), v =
  as.3vel(c(0.4,-0.2,0)) + as.3vel(c(-0.4,0.6,0)) *
  seq(from=0,to=3,len=28) )
```

```{r fc3, fig.cap='Failure of associativity.  Consider the bold arrows.  These show two paths corresponding to u+(v+w) in black, and (u+v)+w in blue.  As the speed of the blue velocities increases, the mismatch becomes larger and larger'}
jj <- as.3vel(c(0.2,0.1,0))
kk <- as.3vel(c(.3,0.5,0))
u <- as.3vel(c(0.4,0,0))
v <- jj + kk*seq(from=0,to=2,len=18)
w <- as.3vel(c(-0.9,0.2,0))
ass_fail(u=u, v=v, w=w, bold=4)
```


